query VaccinationCenters {
  vaccinationCenters {
    name
    appointments {
      time
    }
    vaccines {
      name
      doseCount
    }
    location {
      latitude
      longitude
    }
  }
}
